### ISSUE TITLE
Using it to Program an Arduino Nano Every

### ISSUE THREAD

**Issue by Timo-Weike** [christophevg/reactive-c#1]
Hello,

I really like this approch to program in a reactive manner in C. 
I would like to use this in an Arduino project of mine and wanted to ask if there is any experience in using it for this.

I would expect that I need to use the source code and compile it using the Arduino IDE to upload it to the board.

Since in the read me you spoke of embedded systems. Did you ever consider what memory overhead the lib produces in the program code as well as at runtime?

Also since the last commit is 7 years old, what is the state of the current master branch? Is it somewhat stable or should I expect some bugs and glitches if used on a microcontroller board?

**Comment by christophevg** [comment]
Hi Timo,

whoa, what a blast from the past ;-) I actually had to read through my own [README](https://github.com/christophevg/reactive-c/blob/master/README.md) to refresh my memory and I was actually thinking at certain moments "did I actually write all of this?". I almost got to the point where I felt like grabbing an Arduino from my shelf and try to run reactive-c on it. Sadly, I really don't have the time to do this right now.

I remember why I did this experiment: it was actually exactly my goal to use it to build a reactive "operating system"-like concept on an embedded platform (I was targeting the ATMEGA directly at the time, which is the same underlying MCU-familiy Arduino is targeting). So I would expect that the code in this repo should be very easily "ported" to such platform. (Oh, I'm so tempted to try it myself right now - it's been years since I did some actual C coding and my fingers are itching ;-) - too bad I _really_ don't have the time :-()

As far as I can tell from my own [README](https://github.com/christophevg/reactive-c/blob/master/README.md) (proofs once again how valuable they are) I'd suspect that the code is rather stable (seems I even fixed the glitching problem). Mind that it's an experiment, it _will_ beyond any doubt require some "porting". 

Looking at the [TODO](https://github.com/christophevg/reactive-c/blob/master/TODO) file, I see that there were still a lot of topics I wanted to cover, clearly more advanced stuff, which I wanted to experiment with. I currently don't have the necessary RP knowledge actively in my mind to interpret most of it. It would really require some days to get back in the game and wrap my head around all the RP details. 

So, I'd say, grab the code (maybe piece by piece) and try rebuilding the examples one by one on an Arduino, and see how deep the rabbit hole goes. And if you get anything working... let me know!

Good luck,
Christophe
